In [1]:
import numpy as np

In [4]:
data = np.random.randn(10, 12)
data

array([[ 1.64131285, -0.11946047,  0.09199506,  0.10276888,  0.30829097,
         0.38619065, -0.88866855,  0.41662738,  1.90804218,  1.72049492,
        -1.45865048, -0.73177477],
       [ 1.55578284,  0.61214977, -1.58735188, -0.3835633 ,  0.62053038,
        -1.28951762,  1.23761223,  0.74552872,  0.57411197, -0.61415006,
        -0.38378071, -0.97583228],
       [-0.60586262,  0.97815132, -0.60419039,  1.3793009 , -0.75569516,
         0.93027459, -0.21889848, -0.24028922, -0.55035732, -0.78362245,
        -0.49660942, -2.19925795],
       [ 0.95721168, -0.69348194,  0.2300082 , -1.49994663,  0.30184911,
        -2.1740169 ,  1.38841567, -0.10810842, -0.97563949, -0.25936559,
         0.14857573, -1.62047463],
       [-0.93979206,  0.40722596, -1.43730044,  1.14984446,  0.87481735,
         0.58793296,  1.44821002, -0.50460702, -0.1316271 , -0.45660254,
         1.03817173, -1.05072762],
       [ 1.17929972, -0.15285842,  0.22210388,  0.19723974,  0.9237841 ,
        -1.40058535,  

shape

In [5]:
data.shape

(10, 12)

In [6]:
data.dtype

dtype('float64')

In [8]:
new=[1,2,3,4,5,6,7,8,9]
data1=np.array(new)
data1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype


dtype('float64')

In [13]:
arr2.dtype

dtype('int32')

Arithmetic

In [16]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
print(arr*arr)

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [18]:
print(arr-arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
print(arr+arr)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [20]:
print(arr/arr)

[[1. 1. 1.]
 [1. 1. 1.]]


2d

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
arr2d[2]

array([7, 8, 9])

In [23]:
arr2d[0, 2]

3