In [4]:
import numpy as np 


In [6]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 160]


In [8]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  

In [10]:
print ('First array:') 
print (a) 
print ('\n')  
   
print ('Second array:') 
print (b )
print ('\n')  
   
print ('First Array + Second Array') 
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [12]:
A = np.array([[11, 22, 33], [10, 20, 30]])
print(A)
 


[[11 22 33]
 [10 20 30]]


In [13]:
b = 4
print(b)
 
C = A + b
print(C)

4
[[15 26 37]
 [14 24 34]]
