In [7]:
import numpy as np
from numpy import linalg as geek

In [2]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])


Rank of a Matrix

In [3]:
print("Rank of A:", np.linalg.matrix_rank(A))


Rank of A: 3


Trace of a Matrix

In [4]:
print("\nTrace of A:", np.trace(A))


Trace of A: 11


Determinant of a matrix

In [5]:
print("\nDeterminant of A:", np.linalg.det(A))


Determinant of A: -306.0


Inverse

In [6]:
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))


Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


Eigen Value

In [12]:
a = np.diag((1, 2, 3))
print(a)
c, d = geek.eig(a)
 
print("\nEigen value is :",c)
print("Eigen value is :",d)

[[1 0 0]
 [0 2 0]
 [0 0 3]]

Eigen value is : [1. 2. 3.]
Eigen value is : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Statistical Functions

In [14]:
a = np.array([[2,10,20],[80,43,31],[22,43,10]]) 
print(a)

[[ 2 10 20]
 [80 43 31]
 [22 43 10]]


In [22]:
print("\nThe minimum element among the array:",np.amin(a))  
print("The maximum element among the array:",np.amax(a))  
 


The minimum element among the array: 2
The maximum element among the array: 80


In [26]:
print("\nptp value along axis 1:",np.ptp(a,1))  
  
print("ptp value along axis 0:",np.ptp(a,0))


ptp value along axis 1: [18 49 33]
ptp value along axis 0: [78 33 21]


Percentile

In [27]:
print("\nPercentile along axis 0",np.percentile(a, 10,0))  
  
print("Percentile along axis 1",np.percentile(a, 10, 1))  


Percentile along axis 0 [ 6.  16.6 12. ]
Percentile along axis 1 [ 3.6 33.4 12.4]


Mean, Median and Average

In [28]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
  
print("Array:\n",a)  
  
print("\nMedian of array along axis 0:",np.median(a,0))  
print("Mean of array along axis 0:",np.mean(a,0))  
print("Average of array along axis 1:",np.average(a,1))  

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Median of array along axis 0: [4. 5. 6.]
Mean of array along axis 0: [4. 5. 6.]
Average of array along axis 1: [2. 5. 8.]
